### ISSUE TITLE
Run SegmentCreation 

### ISSUE THREAD

**Issue by caozhenhuamail** [linkedin/pinot#123] opened 2016-05-18 04:56 UTC
when I run SegmentCreation command. the hadoop history error logs as bellow;

how to fix the issue?

Error: org.codehaus.jackson.map.JsonMappingException: N/A (through reference chain: com.linkedin.pinot.common.data.Schema["timeFieldSpec"]->com.linkedin.pinot.common.data.TimeFieldSpec["defaultNullValue"]) at org.codehaus.jackson.map.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:304) at org.codehaus.jackson.map.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:287) at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.set(SettableBeanProperty.java:372) at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:362) at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:494) at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:350) at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:258) at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:362) at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:494) at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:350) at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2402) at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1602) at com.linkedin.pinot.hadoop.job.mapper.HadoopSegmentCreationMapReduceJob$HadoopSegmentCreationMapper.map(HadoopSegmentCreationMapReduceJob.java:123) at com.linkedin.pinot.hadoop.job.mapper.HadoopSegmentCreationMapReduceJob$HadoopSegmentCreationMapper.map(HadoopSegmentCreationMapReduceJob.java:44) at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146) at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787) at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341) at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164) at java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.Subject.doAs(Subject.java:415) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657) at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158) Caused by: java.lang.NullPointerException at com.linkedin.pinot.common.data.TimeFieldSpec.getDataType(TimeFieldSpec.java:85) at com.linkedin.pinot.common.data.PinotDataType.getPinotDataType(PinotDataType.java:1877) at com.linkedin.pinot.common.data.FieldSpec.defaultNullValueFromString(FieldSpec.java:137) at com.linkedin.pinot.common.data.FieldSpec.setDefaultNullValue(FieldSpec.java:123) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.set(SettableBeanProperty.java:370) 

job.properties
# === Index segment creation job config ===

# path.to.input: Input directory containing Avro files
path.to.input=/gobblintest/job-output/eventolap/eventOLAP

# path.to.output: Output directory containing Pinot index segments
path.to.output=/fht-segments/temp/output

# path.to.schema: Schema file for the table, stored locally
path.to.schema=/opt/pinot_config/fht_pinot_schema.json

# segment.table.name: Name of the table for which to generate index segments
segment.table.name=eventOLAP

/opt/pinot_config/fht_pinot_schema.json

{
  "metricFieldSpecs" : [
    {
      "dataType" : "INT",
      "delimiter" : null,
      "name" : "event_count"
    }
  ],
  "dimensionFieldSpecs" : [
    {
      "dataType" : "STRING",
      "delimiter" : null,
      "name" : "plat_id"
    },
    {
      "dataType" : "STRING",
      "delimiter" : null,
      "name" : "event_name"
    },
    {
      "dataType" : "STRING",
      "delimiter" : null,
      "name" : "event_key"
    },
    {
      "dataType" : "STRING",
      "delimiter" : null,
      "name" : "open_id"
    },
    {
      "dataType" : "STRING",
      "delimiter" : null,
      "name" : "city"
    },
    {
      "dataType" : "STRING",
      "delimiter" : null,
      "name" : "province"
    },
    {
      "dataType" : "STRING",
      "delimiter" : null,
      "name" : "country"
    },
    {
      "dataType" : "INT",
      "delimiter" : null,
      "name" : "sex"
    },
    {
      "dataType" : "INT",
      "delimiter" : null,
      "name" : "group_id"
    }
  ],
  "timeFieldSpec" : {
    "incomingGranularitySpec" : {
      "timeType" : "MILLISECONDS",
      "dataType" : "LONG",
      "name" : "create_time"
    },
    "outgoingGranularitySpec" : {
      "dataType": "LONG",
      "timeType": "MILLISECONDS",
      "name": "create_time"
    }
  },
  "schemaName" : "eventOLAP"
}

/gobblintest/job-output/eventolap/eventOLAP/.avro 

{"city":"yiggVwsCvy", "country":"BLVlDVqCFk", "create_time":1463544194, "event_count":379, "event_key":"MdtvIBrvNp", "event_name":"jsubFvQPzK","group_id":290,"open_id":1, "plat_id":"eUTRlQcXqH", "province":"GJUMcENXmA", "sex":42}{"city":"yiggVwsCvy", "country":"BLVlDVqCFk", "create_time":1463544194, "event_count":379, "event_key":"MdtvIBrvNp", "event_name":"jsubFvQPzK","group_id":290,"open_id":1, "plat_id":"eUTRlQcXqH", "province":"GJUMcENXmA", "sex":42}{"city":"yiggVwsCvy", "country":"BLVlDVqCFk", "create_time":1463544194, "event_count":379, "event_key":"MdtvIBrvNp", "event_name":"jsubFvQPzK","group_id":290,"open_id":1, "plat_id":"eUTRlQcXqH", "province":"GJUMcENXmA", "sex":42}

**Comment by raviarin** [comment] 2016-05-26 22:52
@Jackie-Jiang Would you be able to take a look at this?

**Comment by Jackie-Jiang** [comment] 2016-05-26 23:15
Hi, I checked at the exception stacktrace, and it seems that the exception was thrown out from ObjectMapper when trying to read value from schema json file. I tried it locally and it reads the value correctly. Can you please first retry with the latest version pinot? If that still does not work, can you provide more details on what command you run?

**Comment by laloyd** [comment] 2016-06-10 20:11
I have a similar issue too using the flights schema from june 9th 2016 build

stacktrace : 
16/06/10 11:59:03 INFO mapred.LocalJobRunner: map task executor complete.
16/06/10 11:59:03 WARN mapred.LocalJobRunner: job_local969390209_0001
java.lang.Exception: org.codehaus.jackson.map.JsonMappingException: N/A (through reference chain: com.linkedin.pinot.common.data.Schema["timeFieldSpec"]->com.linkedin.pinot.common.data.TimeFieldSpec["defaultNullValue"])
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522)
Caused by: org.codehaus.jackson.map.JsonMappingException: N/A (through reference chain: com.linkedin.pinot.common.data.Schema["timeFieldSpec"]->com.linkedin.pinot.common.data.TimeFieldSpec["defaultNullValue"])
	at org.codehaus.jackson.map.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:345)
	at org.codehaus.jackson.map.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:328)
	at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.set(SettableBeanProperty.java:424)
	at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:414)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
	at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299)
	at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:414)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2732)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1863)
	at com.linkedin.pinot.hadoop.job.mapper.HadoopSegmentCreationMapReduceJob$HadoopSegmentCreationMapper.map(HadoopSegmentCreationMapReduceJob.java:123)
	at com.linkedin.pinot.hadoop.job.mapper.HadoopSegmentCreationMapReduceJob$HadoopSegmentCreationMapper.map(HadoopSegmentCreationMapReduceJob.java:44)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.linkedin.pinot.common.data.TimeFieldSpec.getDataType(TimeFieldSpec.java:85)
	at com.linkedin.pinot.common.data.PinotDataType.getPinotDataType(PinotDataType.java:1877)
	at com.linkedin.pinot.common.data.FieldSpec.defaultNullValueFromString(FieldSpec.java:137)
	at com.linkedin.pinot.common.data.FieldSpec.setDefaultNullValue(FieldSpec.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.set(SettableBeanProperty.java:422)
	... 20 more





And schema file:

pinot-0.016-pkg laloyd$ cat sample_data/flights/flights-schema.json
{
  "dimensionFieldSpecs" : [
    {
      "name": "Year",
      "dataType" : "INT",
      "delimiter" : null,
      "singleValueField" : true
    },
    {
      "name": "Month",
      "dataType" : "INT",
      "delimiter" : null,
      "singleValueField" : true
    },
    {
      "name": "Carrier",
      "dataType" : "STRING",
      "delimiter" : null,
      "singleValueField" : true
    },
    {
      "name": "Origin",
      "dataType" : "STRING",
      "delimiter" : null,
      "singleValueField" : true
    },
    {
      "name": "Dest",
      "dataType" : "STRING",
      "delimiter" : null,
      "singleValueField" : true
    },
    {
      "name": "DivAirports",
      "dataType" : "STRING",
      "delimiter" : null,
      "singleValueField" : false
    }
  ],
  "timeFieldSpec" : {
    "incomingGranularitySpec" : {
      "timeType" : "DAYS",
      "dataType" : "INT",
      "name" : "DaysSinceEpoch"
    }
  },
  "metricFieldSpecs" : [
    {
      "name" : "Delayed",
      "dataType" : "INT",
      "delimiter" : null,
      "singleValueField" : true
    },
    {
      "name" : "Cancelled",
      "dataType" : "INT",
      "delimiter" : null,
      "singleValueField" : true
    },
    {
      "name" : "Diverted",
      "dataType" : "INT",
      "delimiter" : null,
      "singleValueField" : true
    }
   ],
  "schemaName" : "flights"
}
SFO-M-PLLOYD02:pinot-0.016-pkg laloyd$

**Comment by laloyd** [comment] 2016-06-10 20:32
during mvn package I saw this too:

es/jdk1.8.0_51.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Running com.linkedin.pinot.common.TestSchema
file:/Users/laloyd/src/3rdparty/pinot/pinot-common/target/test-classes/data1.schema
Not extracting plain file file:/Users/laloyd/src/3rdparty/pinot/pinot-common/target/test-classes/data1.schema
defaultNullValueFromString  value -1
defaultNullValueFromString  value
defaultNullValueFromString  value -1
defaultNullValueFromString  value
defaultNullValueFromString  value -1.0
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.772 sec <<< FAILURE! - in com.linkedin.pinot.common.TestSchema
test2(com.linkedin.pinot.common.TestSchema)  Time elapsed: 0.087 sec  <<< FAILURE!
org.codehaus.jackson.map.JsonMappingException: N/A (through reference chain: com.linkedin.pinot.common.data.Schema["metricFieldSpecs"]->com.linkedin.pinot.common.data.MetricFieldSpec["defaultNullValue"])
	at com.linkedin.pinot.common.TestSchema.test2(TestSchema.java:59)
Caused by: java.lang.NullPointerException
	at com.linkedin.pinot.common.TestSchema.test2(TestSchema.java:59)

**Comment by kishoreg** [comment] 2016-06-10 20:46
Looking into it.

**Comment by laloyd** [comment] 2016-06-10 21:26
Thanks

**Comment by Jackie-Jiang** [comment] 2016-06-14 23:52
Do you still have this issue? I tried loading the schema you provide, and run the test on both linux and mac, but still cannot reproduce the problem.

**Comment by caozhenhuamail** [comment] 2016-06-15 06:55
/pinot/pinot-common/src/main/java/com/linkedin/pinot/common/data/TimeFieldSpec.java

I  update code as below:

//  @Override
//  public DataType getDataType() {
//    return getOutgoingGranularitySpec().getDataType();
//  }

then it can be work.

**Comment by Jackie-Jiang** [comment] 2016-06-15 18:02
@caozhenhuamail Thanks for this message, this can narrow down the debugging range a lot. Working on that now.

**Comment by Jackie-Jiang** [comment] 2016-06-16 23:05
Find the root cause of this issue. In the FieldSpec setter method setDefaultNullValue(Object value), when value is not null, it will call getDataType(), which will be set by another setter method. For TimeFieldSpec, it depends on the outgoingGranularitySpec data type, and will throw a NPE if outgoingGranularitySpec is not set yet. The correctness of FieldSpec serialize and deserialize highly depends on the order of execution of the setter methods. Will find a way to fix it shortly.

**Comment by caozhenhuamail** [comment] 2016-06-18 11:54
if the bug be fixed  . I just pull the new code and find the problem still exist.

**Comment by Jackie-Jiang** [comment] 2016-06-18 19:29
Not yet. Will leave a comment when the bug fix shipped.

**Comment by Jackie-Jiang** [comment] 2016-06-23 23:44
@caozhenhuamail The fix has been merged, can you try again? Thanks.

**Closed** 2016-07-11 18:03 UTC
